# Generated by Django 3.2.5 on 2022-08-03 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cellar',
            new_name='Winery',
        ),
    ]
